import React, { useState } from 'react';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import { Session } from '../auth';
const API = process.env.REACT_APP_API_URL || 'http://localhost:9000';
export default function SearchPage({ session, onLogout }: { session: Session; onLogout: () => void }) {
  const [query, setQuery] = useState(''); const [results, setResults] = useState<any[]>([]); const [searched, setSearched] = useState(false); const [loading, setLoading] = useState(false); const navigate = useNavigate();
  const search = async () => { if (!query.trim()) return; setLoading(true); try { setResults((await axios.get(`${API}/api/documents/search`, { params: { query }, headers: { Authorization: `Bearer ${session.token}` } })).data); setSearched(true); } catch { alert('Search failed.'); } finally { setLoading(false); } };
  return <div className="portal-layout"><nav className="portal-nav"><div className="nav-brand">🏥 MED AI — Doctor Portal</div><div className="nav-right"><span className="doctor-name">👤 {session.username}</span><button className="logout-btn" onClick={onLogout}>Sign out</button></div></nav><main className="portal-content"><div className="search-hero"><h1>Patient Record Search</h1><p>Search approved medical reports by patient name or patient ID.</p><div className="search-bar"><input className="search-input" placeholder="Patient name or ID" value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === 'Enter' && search()} /><button className="search-btn" onClick={search} disabled={loading}>{loading ? 'Searching…' : '🔍 Search'}</button></div></div>{searched && <div className="results-section">{!results.length ? <div className="no-results">No approved reports found for “{query}”.</div> : <><p className="results-count">{results.length} approved report(s) found</p><div className="results-grid">{results.map(doc => { const patient = (doc.validated_data || doc.extracted_data)?.patient_information || {}; return <div className="result-card" key={doc.id} onClick={() => navigate(`/patient/${doc.id}`)}><div className="card-header"><span className="patient-name">{patient.full_name || 'Unknown patient'}</span><span className="patient-id">{patient.patient_identifier || '—'}</span></div><div className="card-details"><span>DOB: {patient.date_of_birth || '—'}</span><span>Sex: {patient.sex || '—'}</span></div><div className="card-footer"><span>📄 {doc.file_name}</span><span className="view-link">View report →</span></div></div>; })}</div></>}</div>}</main></div>;
}
